### ISSUE TITLE
UI Loader needed, 150 seconds before first page render

### ISSUE THREAD

**Issue by tarekeldeeb** [Tarteel-io/tarteel.io#100]
When the tarteel.io is opened, it needs too long to render the first HTML view.
I think a simple loading applet should show as soon as possible.

Claiming to have a better than average internet speed (10Mbps), I was tricked the first time that the site was down, but when I opened the debugging sidebar (F12) I noticed that `data.js` is still loading.

It took 150 seconds to render the landing page, which cannot be acceptable.
![slow_load](https://user-images.githubusercontent.com/90985/45160009-9f6c3d00-b1e8-11e8-83ea-bdc47fb1edeb.JPG)

**Comment by tifa2UP** [comment]
+1, thanks @tarekeldeeb!

**Comment by tifa2UP** [comment]
@bahaa96 want to pick this up?

**Comment by mohamedgomran** [comment]
I suggest:
Splitting HTML index files and only load the part when its needed.
Remove duplicate imports of js files.
Delivering js only when it's needed.
Using the minified verstion of jQuery instead of current un-minified one.
Refactoring the JS files (in terms of code).
Delivering a minified js files for users in production while keeping the original in development.

**Comment by mohamedgomran** [comment]
I suggest:

- Splitting HTML index files and only load the part when its needed.
- Remove duplicate imports of JS files.
- Delivering JS only when it's needed (JS costs the browser a lot).
- Using the minified version of jQuery instead of current un-minified one.
- Refactoring the JS files (in terms of code).
- Delivering a minified JS files for users in production while keeping the original in development.

**Comment by tarekeldeeb** [comment]
Hey Mohamed,

I suggest you focus on the major cause; loading data.js before loading the view.
Other JS files, are relatively much smaller.

Regards,

**Comment by mohamedgomran** [comment]
This raise a question, Why we have to load the whole Quran text (data.js) in one request?

**Comment by mohamedgomran** [comment]
This raises a question, Why we have to load the whole Quran text (data.js) in one request?

**Comment by MohammedEssehemy** [comment]
I've opened pull request to add async to the script tag in html so that it won't prevent other scripts from loading, also we should consider gzip the server response but I don't have as much experience in django @mohamedgomran can you help in this?

**Comment by mohamedgomran** [comment]
@MohammedEssehemy You mean gzipping the data.js response?

**Comment by MohammedEssehemy** [comment]
@mohamedgomran I mean something like this [GZip middleware](https://docs.djangoproject.com/en/2.1/ref/middleware/#module-django.middleware.gzip)

**Comment by mohamedgomran** [comment]
@MohammedEssehemy Thanks Mohammed, but it has a lot of security issues as mentioned in the docs.

**Comment by piraka9011** [comment]
I've minified all CSS & JS per @mohamedgomran's suggestion using YUI Compressor and did some refactoring so that minified versions are used in page. Will ref. in a pull request.

I've been using the file watcher feature in PyCharm/WebStorm to do this automatically, however, I can include a script to automate this.

**Comment by abidlabs** [comment]
I believe this issue is closed, correct? @tarekeldeeb can you confirm you're no longer experiencing the severe delay?

**Comment by mohamedgomran** [comment]
@piraka9011  Can you please replace the jQuery with the minified version in your PR?

**Comment by piraka9011** [comment]
Will do!

Also it looks like some refactoring is in order in `script.js` (lines 315, 545) if we want to not load `data.js`. Maybe create an api endpoint where it's requested instead? I can probably do that, but whoever wrote the `getSurah` and `navigateToChangeAyah` might be more suitable.

**Comment by abidlabs** [comment]
With your minifying changes @piraka9011, I think this is good now.
