### ISSUE TITLE
Bug in dataset download script.

### ISSUE THREAD

**Issue by abidlabs** [Tarteel-io/tarteel.io#151]
I receive a `MultipleObjectsReturned at /download-full-dataset-csv/` 

when I try to access https://www.tarteel.io/download-full-dataset-csv/.

@khanh111 can you take a look?

**Comment by piraka9011** [comment]
It appears that the session_id is not unique, so you get multiple objects. @khanh111 try using the primary key `id` instead.
Thinking about it a bit more, I think we should use a foreign key to link Demographics to recordings since that would be much more cleaner.
Example [here](https://github.com/Tarteel-io/tarteel.io/blob/a0159252e3d9682d86c2f1e5885a5c2a2fc01d2e/evaluation/models.py#L58).

**Comment by abidlabs** [comment]
I think this solution is fine. If people have multiple demographic form submits, let's use the latest version.
