### ISSUE TITLE
Discussion: User experience of Qir'ah choice

### ISSUE THREAD

**Issue by tifa2UP** [Tarteel-io/tarteel.io#97]

**Comment by mohamedgomran** [comment]
My be it can be like the Hertage choice with search feature to make it easier.
Putting it in a separate row would be nice as some names (like: Ibn Dhakwan) are wrapped due to the width.
About Gender, radio buttons would me more convenient, only one click needed, also why we have an option "others" in gender?

**Comment by bahaa96** [comment]
We'll work more on this section thanks for your feedback. 😘

**Comment by abidlabs** [comment]
Looks like this is live now. Should we close this @bahaa96?

**Comment by abidlabs** [comment]
Looks good to me.
